# Generated by Django 3.1.1 on 2020-10-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupkey',
            name='sign_up_key',
            field=models.CharField(default='75110410210', editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کلید ثبت نام'),
        ),
    ]
