# Generated by Django 3.1.1 on 2020-10-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201022_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show_on_login',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه ورود'),
        ),
        migrations.AddField(
            model_name='notification',
            name='show_on_signup',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه ثبت نام'),
        ),
        migrations.AlterField(
            model_name='signupkey',
            name='sign_up_key',
            field=models.CharField(default='814kUP48', editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کلید ثبت نام'),
        ),
    ]
