# Generated by Django 3.1.1 on 2020-11-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201101_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='klass',
            field=models.ManyToManyField(to='dashboard.Klass', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='signupkey',
            name='sign_up_key',
            field=models.CharField(default='SVjt68gs', editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کلید ثبت نام'),
        ),
    ]
