# Generated by Django 3.1.1 on 2020-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201101_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klass',
            name='teacher',
        ),
        migrations.AddField(
            model_name='klass',
            name='teacher',
            field=models.ManyToManyField(related_name='klass_teacher', to='dashboard.Profile', verbose_name='آموزگار (ها)'),
        ),
        migrations.AlterField(
            model_name='signupkey',
            name='sign_up_key',
            field=models.CharField(default='210Jfw2105', editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کلید ثبت نام'),
        ),
    ]
