# Generated by Django 3.1.1 on 2020-12-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201101_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='notification_title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_image',
            field=models.ImageField(blank=True, null=True, upload_to='notification_pics/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_text',
            field=models.TextField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='notification',
            name='show_on_dashboard',
            field=models.BooleanField(default=False, verbose_name='نمایش در داشبورد'),
        ),
        migrations.AlterField(
            model_name='signupkey',
            name='sign_up_key',
            field=models.CharField(default='5O6BN927', editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کلید ثبت نام'),
        ),
    ]
