# Generated by Django 3.1.1 on 2020-12-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20201218_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='signupkey',
            name='sign_up_key',
            field=models.CharField(default='kDvmdpyp', editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کلید ثبت نام'),
        ),
    ]
