# Generated by Django 3.1.1 on 2020-12-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20201218_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupkey',
            name='sign_up_key',
            field=models.CharField(default='jD1010100Ne', editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کلید ثبت نام'),
        ),
    ]
